name: update attempts (reviewer)

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  
defaults:
  run:
    shell: pwsh
env:
  GITHUB_TOKEN: ${{ secrets.VAR_TOKEN }}

jobs:
  update_attempts:    
    if: >-
      (contains(fromJSON('["26046784", "96750568", "48153570", "44366841", "49571700"]'), github.actor_id) 
      && github.event_name == 'workflow_dispatch')
      || (github.event_name == 'pull_request_review'
      && (github.event.review.state == 'APPROVED'
      || github.event.review.state == 'CHANGES_REQUESTED'))
      
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - name: update_attempts
        run: |
          ## The token must have the following permission set:
          ## actions_variables:write and environments:write   

          $OWNER = '${{ github.repository_owner }}'
          $REPO = '${{ github.event.repository.name }}'
          $REPOSITORY_ID = '${{ github.event.repository.id }}'
          $WORKFLOW_ID = "ci.yaml"
          
          echo "PRINT current RUN_NUMBER"
          ${{ vars.RUN_NUMBER }}

          echo "PRINT add RUNS"
          ${{ vars.LW1_RUNS_PER_ATTEMPT }}

          $runs = gh api `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/$OWNER/$REPO/actions/runs | ConvertFrom-Json

          $run_number_max = 0; 
          foreach ($run in $runs.workflow_runs) 
          { 
            #$run.path; $run.run_number; ($run.path).Contains("ci.yaml"); 
            if (($run.path).Contains("ci.yaml") -and [int]($run.run_number) -gt $run_number_max) 
            { 
              $run_number_max = [int]($run.run_number) 
            }
          }
          
          echo "PRINT run_number_max yaml"
          $run_number_max

          $vari = ${{ vars.LW1_RUNS_PER_ATTEMPT }} + $run_number_max

          gh api `
            --method PATCH `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/$OWNER/$REPO/actions/variables/RUN_NUMBER `
            -f name='RUN_NUMBER' `
            -f value=$vari

          echo "PRINT new RUN_NUMBER"
          $vari

          echo "dbg"
          (gh api `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/$OWNER/$REPO/actions/variables/RUN_NUMBER | ConvertFrom-Json).value


          $WORKFLOW_ID = "ci.yaml"
          # https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#get-workflow-usage
          gh api `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_ID/timing
            
